Update Bazel, upstream rules
As a part of this, propogate original libraries so they are passed to the linker in the object list, avoiding argmax issues that come from new starlark transitions in rules_apple

Also, handle those transitions in generated Xcode projects

diff --git a/tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/installer b/tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/installer
--- a/tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/installer
+++ b/tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/installer
@@ -9,50 +9,58 @@ set -eux
 find "${BAZEL_DIAGNOSTICS_DIR}" -type f -atime +7d -delete
 
 case "${PRODUCT_TYPE}" in
-    com.apple.product-type.framework)
-        input_options=("bazel-bin/$BAZEL_BIN_SUBDIR/${TARGET_NAME}/${FULL_PRODUCT_NAME}")
-        ;;
-    com.apple.product-type.framework.static)
-	    # For static library, as the output is not under bazel-bin, we have to get it based on build event
-        # Example of such entry inside build event:
-        # important_output {
-        #   name: ".../SomeFramework.framework/SomeFramework"
-        #   uri: "file:///private/var/tmp/.../.../SomeFramework.framework/SomeFramework"
-        #   path_prefix:... 
-        #   ...
-        #  } 
-        # We only care about the entry ending with TARGET_NAME" so that we can get the path to its directory
-        QUERY=`grep -A 2 important_output "$BAZEL_BUILD_EVENT_TEXT_FILENAME" | grep -w uri | grep ${TARGET_NAME}\" | sed "s/uri: \"file:\/\///"`
-        if [[ -z $QUERY ]]; then 
-            echo "Unable to locate resource for framework of ${TARGET_NAME}"
-            exit 1
-        fi
-        input_options=($(dirname "${QUERY}"))
-        ;;
-    com.apple.product-type.bundle.unit-test)
-        input_options=("bazel-bin/$BAZEL_BIN_SUBDIR/${FULL_PRODUCT_NAME}" "bazel-bin/$BAZEL_BIN_SUBDIR/$TARGET_NAME.__internal__.__test_bundle_archive-root/$TARGET_NAME${WRAPPER_SUFFIX:-}")
-        ;;
-    com.apple.product-type.application)
-        input_options=("bazel-bin/$BAZEL_BIN_SUBDIR/${FULL_PRODUCT_NAME}" "bazel-bin/$BAZEL_BIN_SUBDIR/${TARGET_NAME}_archive-root/Payload/$TARGET_NAME${WRAPPER_SUFFIX:-}")
-        ;;
-    *)
-        echo "Error: Installing ${TARGET_NAME} of type ${PRODUCT_TYPE} is unsupported" >&2
+com.apple.product-type.framework)
+    input_options=("bazel-bin/$BAZEL_BIN_SUBDIR/${TARGET_NAME}/${FULL_PRODUCT_NAME}")
+    ;;
+com.apple.product-type.framework.static)
+    # For static library, as the output is not under bazel-bin, we have to get it based on build event
+    # Example of such entry inside build event:
+    # important_output {
+    #   name: ".../SomeFramework.framework/SomeFramework"
+    #   uri: "file:///private/var/tmp/.../.../SomeFramework.framework/SomeFramework"
+    #   path_prefix:...
+    #   ...
+    #  }
+    # We only care about the entry ending with TARGET_NAME" so that we can get the path to its directory
+    QUERY=$(grep -A 2 important_output "$BAZEL_BUILD_EVENT_TEXT_FILENAME" | grep -w uri | grep ${TARGET_NAME}\" | sed "s/uri: \"file:\/\///")
+    if [[ -z $QUERY ]]; then
+        echo "Unable to locate resource for framework of ${TARGET_NAME}"
         exit 1
-        ;;
+    fi
+    input_options=($(dirname "${QUERY}"))
+    ;;
+com.apple.product-type.bundle.unit-test)
+    input_options=(
+        "bazel-bin/$BAZEL_BIN_SUBDIR/${FULL_PRODUCT_NAME}"
+        "bazel-bin/$BAZEL_BIN_SUBDIR/$TARGET_NAME.__internal__.__test_bundle_archive-root/$TARGET_NAME${WRAPPER_SUFFIX:-}"
+        "bazel-bin/$BAZEL_BIN_SUBDIR/${BAZEL_BUILD_TARGET_LABEL#*:}.runfiles/${BAZEL_BUILD_TARGET_WORKSPACE}/${BAZEL_BIN_SUBDIR}/${FULL_PRODUCT_NAME}"
+    )
+    ;;
+com.apple.product-type.application)
+    input_options=(
+        "bazel-bin/$BAZEL_BIN_SUBDIR/${FULL_PRODUCT_NAME}"
+        "bazel-bin/$BAZEL_BIN_SUBDIR/${TARGET_NAME}_archive-root/Payload/$TARGET_NAME${WRAPPER_SUFFIX:-}"
+        "bazel-bin/$BAZEL_BIN_SUBDIR/${BAZEL_BUILD_TARGET_LABEL#*:}.runfiles/${BAZEL_BUILD_TARGET_WORKSPACE}/${BAZEL_BIN_SUBDIR}/${FULL_PRODUCT_NAME}"
+    )
+    ;;
+*)
+    echo "Error: Installing ${TARGET_NAME} of type ${PRODUCT_TYPE} is unsupported" >&2
+    exit 1
+    ;;
 esac
 output="$TARGET_BUILD_DIR/$FULL_PRODUCT_NAME"
 
 mkdir -p $OBJECT_FILE_DIR_normal/$CURRENT_ARCH/
 chmod -R +w $OBJECT_FILE_DIR_normal/$CURRENT_ARCH/
 
-for swiftmodulefile in ${BAZEL_SWIFTMODULEFILES_TO_COPY:-}; do 
-	if [[ -e $swiftmodulefile ]]; then
-		cp $swiftmodulefile $OBJECT_FILE_DIR_normal/$CURRENT_ARCH/
-  	fi
+for swiftmodulefile in ${BAZEL_SWIFTMODULEFILES_TO_COPY:-}; do
+    if [[ -e $swiftmodulefile ]]; then
+        cp $swiftmodulefile $OBJECT_FILE_DIR_normal/$CURRENT_ARCH/
+    fi
 done
 
-
 mkdir -p "$(dirname "$output")"
+copied=false
 
 for input in "${input_options[@]}"; do
     if [[ -z $input ]] || [ $input = "." ] || [ $input = "/" ]; then
@@ -70,22 +78,22 @@ for input in "${input_options[@]}"; do
 
     rsync \
         --recursive --chmod=u+w --delete \
-        "$input" "$output" > "$BAZEL_DIAGNOSTICS_DIR"/rsync-stdout-"$DATE_SUFFIX".log 2> "$BAZEL_DIAGNOSTICS_DIR"/rsync-stderr-"$DATE_SUFFIX".log
-	if [[ -n ${SWIFT_OBJC_INTERFACE_HEADER_NAME:-} ]]
-	then
-		cp -f $input/Headers/$SWIFT_OBJC_INTERFACE_HEADER_NAME $OBJECT_FILE_DIR_normal/$CURRENT_ARCH/
-	fi      	
+        "$input" "$output" >"$BAZEL_DIAGNOSTICS_DIR"/rsync-stdout-"$DATE_SUFFIX".log 2>"$BAZEL_DIAGNOSTICS_DIR"/rsync-stderr-"$DATE_SUFFIX".log
+    if [[ -n ${SWIFT_OBJC_INTERFACE_HEADER_NAME:-} ]]; then
+        cp -f $input/Headers/$SWIFT_OBJC_INTERFACE_HEADER_NAME $OBJECT_FILE_DIR_normal/$CURRENT_ARCH/
+    fi
+    copied=true
     break
 done
 
-if [[ ! -d $output ]]; then
+if [[ ! -d "$output" ]] || [[ "$copied" = 'false' ]]; then
     echo "error: failed to find $FULL_PRODUCT_NAME in expected locations: ${input_options[*]}"
     exit 1
 fi
 
-"$BAZEL_INSTALLERS_DIR"/lldb-settings.sh > "$BAZEL_DIAGNOSTICS_DIR"/lldb-stdout-"$DATE_SUFFIX".log 2> "$BAZEL_DIAGNOSTICS_DIR"/lldb-stderr-"$DATE_SUFFIX".log
+"$BAZEL_INSTALLERS_DIR"/lldb-settings.sh >"$BAZEL_DIAGNOSTICS_DIR"/lldb-stdout-"$DATE_SUFFIX".log 2>"$BAZEL_DIAGNOSTICS_DIR"/lldb-stderr-"$DATE_SUFFIX".log
 
 # Part of the build intermediary output will be swiftmodule files
 # which XCode will use for indexing. Let's keep those.
-"$BAZEL_INSTALLERS_DIR"/swiftmodules.sh > "$BAZEL_DIAGNOSTICS_DIR"/swiftmodules-stdout-"$DATE_SUFFIX".log 2> "$BAZEL_DIAGNOSTICS_DIR"/swiftmodules-stderr-"$DATE_SUFFIX".log &
-"$BAZEL_INSTALLERS_DIR"/indexstores.sh > "$BAZEL_DIAGNOSTICS_DIR"/indexstores-stdout-"$DATE_SUFFIX".log 2> "$BAZEL_DIAGNOSTICS_DIR"/indexstores-stderr-"$DATE_SUFFIX".log &
+"$BAZEL_INSTALLERS_DIR"/swiftmodules.sh >"$BAZEL_DIAGNOSTICS_DIR"/swiftmodules-stdout-"$DATE_SUFFIX".log 2>"$BAZEL_DIAGNOSTICS_DIR"/swiftmodules-stderr-"$DATE_SUFFIX".log &
+"$BAZEL_INSTALLERS_DIR"/indexstores.sh >"$BAZEL_DIAGNOSTICS_DIR"/indexstores-stdout-"$DATE_SUFFIX".log 2>"$BAZEL_DIAGNOSTICS_DIR"/indexstores-stderr-"$DATE_SUFFIX".log &
